version: '3.7'
services:
  db:
    image: mysql
    restart: always    
    container_name: mysql-container-lab 
    command: --default-authentication-plugin=mysql_native_password    
    environment:
      MYSQL_ROOT_PASSWORD: adm123456
    volumes:
      - ./db/data:/var/lib/mysql